export const CONTENT_TABLES = [
  {
    section: 'home',
    property: 'services',
    table: 'home_services',
    columns: ['title', 'price', 'copy', 'icon', 'tone', 'image'],
  },
  {
    section: 'home',
    property: 'testimonials',
    table: 'home_testimonials',
    arrayFields: ['name', 'service', 'copy'],
    columns: ['name', 'service', 'copy'],
  },
  {
    section: 'booking',
    property: 'devices',
    table: 'booking_devices',
    columns: ['name', 'image', 'tone', 'brand', 'category'],
  },
  {
    section: 'booking',
    property: 'repairIssues',
    table: 'booking_repair_issues',
    columns: ['key', 'title', 'copy', 'icon', 'tone', 'image', 'availability'],
  },
  {
    section: 'reviews',
    property: 'stats',
    table: 'review_stats',
    columns: ['value', 'label', 'copy', 'icon', 'tone'],
  },
  {
    section: 'reviews',
    property: 'reviews',
    table: 'customer_reviews',
    columns: ['name', 'date', 'copy', 'stars', 'service', 'icon', 'tone', 'avatar'],
  },
  {
    section: 'beforeAfter',
    property: 'repairs',
    table: 'before_after_repairs',
    columns: ['device', 'service', 'copy', 'time', 'tone', 'beforeImage', 'afterImage', 'kind'],
  },
  {
    section: 'beforeAfter',
    property: 'testimonials',
    table: 'before_after_testimonials',
    arrayFields: ['name', 'service', 'copy'],
    columns: ['name', 'service', 'copy'],
  },
  {
    section: 'services',
    property: 'heroTrust',
    table: 'service_hero_trust',
    columns: ['title', 'copy', 'icon', 'tone'],
  },
  {
    section: 'services',
    property: 'services',
    table: 'service_cards',
    columns: ['title', 'copy', 'price', 'image', 'icon', 'tone'],
  },
  {
    section: 'services',
    property: 'trustFeatures',
    table: 'service_trust_features',
    columns: ['title', 'copy', 'icon', 'tone'],
  },
  {
    section: 'services',
    property: 'process',
    table: 'service_process_steps',
    columns: ['title', 'copy', 'icon', 'tone'],
  },
  {
    section: 'support',
    property: 'faqs',
    table: 'support_faqs',
    columns: ['question', 'answer'],
  },
  {
    section: 'support',
    property: 'quickActions',
    table: 'support_quick_actions',
    columns: ['title', 'copy', 'icon', 'tone', 'href'],
  },
  {
    section: 'support',
    property: 'contactInfo',
    table: 'support_contact_info',
    columns: ['title', 'copy', 'icon', 'tone', 'href'],
  },
];

export const CONTENT_SECTION_KEYS = [...new Set(CONTENT_TABLES.map((definition) => definition.section))];

export const CONTENT_RESOURCES = {
  'home-services': 'home_services',
  'home-testimonials': 'home_testimonials',
  'booking-devices': 'booking_devices',
  'repair-issues': 'booking_repair_issues',
  'review-stats': 'review_stats',
  reviews: 'customer_reviews',
  'before-after-repairs': 'before_after_repairs',
  'before-after-testimonials': 'before_after_testimonials',
  'service-trust': 'service_hero_trust',
  services: 'service_cards',
  'service-features': 'service_trust_features',
  'service-process': 'service_process_steps',
  'support-faqs': 'support_faqs',
  'support-actions': 'support_quick_actions',
  'support-contact': 'support_contact_info',
};

export const CONTENT_RESOURCE_DEFINITIONS = CONTENT_TABLES.map((definition) => {
  const resource = Object.entries(CONTENT_RESOURCES).find(([, table]) => table === definition.table)?.[0] ?? definition.table;
  return {
    key: resource,
    endpoint: `/api/${resource}`,
    section: definition.section,
    property: definition.property,
    table: definition.table,
    columns: definition.columns,
  };
});

export function postgresContentTableDdl(definition) {
  const columns = definition.columns.map((column) => `${toSnakeCase(column)} TEXT NOT NULL DEFAULT ''`).join(',\n          ');
  return `
        CREATE TABLE IF NOT EXISTS ${definition.table} (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          ${columns},
          sort_order INTEGER NOT NULL DEFAULT 0,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
      `;
}

export function sqliteContentTableDdl(definition) {
  const columns = definition.columns.map((column) => `${toSnakeCase(column)} TEXT NOT NULL DEFAULT ''`).join(',\n      ');
  return `
    CREATE TABLE IF NOT EXISTS ${definition.table} (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      ${columns},
      sort_order INTEGER NOT NULL DEFAULT 0,
      created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    );
  `;
}

export function toSnakeCase(value) {
  return String(value).replace(/[A-Z]/g, (match) => `_${match.toLowerCase()}`);
}

export function normalizeContentItems(definition, items) {
  return (Array.isArray(items) ? items : []).map((item) => normalizeContentItem(definition, item));
}

export function normalizeContentItem(definition, item) {
  if (definition.arrayFields) {
    const source = Array.isArray(item) ? item : definition.arrayFields.map((field) => item?.[field]);
    return Object.fromEntries(definition.arrayFields.map((field, index) => [field, String(source[index] ?? '')]));
  }

  return Object.fromEntries(definition.columns.map((column) => [column, String(item?.[column] ?? '')]));
}

export function rowToContentItem(definition, row) {
  const item = Object.fromEntries(definition.columns.map((column) => [column, String(row[toSnakeCase(column)] ?? '')]));
  if (definition.arrayFields) {
    return definition.arrayFields.map((field) => item[field] ?? '');
  }
  return item;
}

export function rowToContentRecord(definition, row) {
  return {
    id: Number(row.id),
    sortOrder: Number(row.sort_order ?? 0),
    ...Object.fromEntries(definition.columns.map((column) => [column, String(row[toSnakeCase(column)] ?? '')])),
  };
}

export function definitionsForSection(sectionKey) {
  return CONTENT_TABLES.filter((definition) => definition.section === sectionKey);
}

export function definitionForTable(tableName) {
  return CONTENT_TABLES.find((definition) => definition.table === tableName) ?? null;
}
