BEGIN;

CREATE TABLE IF NOT EXISTS home_services (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL DEFAULT '',
  price TEXT NOT NULL DEFAULT '',
  copy TEXT NOT NULL DEFAULT '',
  icon TEXT NOT NULL DEFAULT '',
  tone TEXT NOT NULL DEFAULT '',
  image TEXT NOT NULL DEFAULT '',
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS home_testimonials (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL DEFAULT '',
  service TEXT NOT NULL DEFAULT '',
  copy TEXT NOT NULL DEFAULT '',
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS booking_devices (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL DEFAULT '',
  image TEXT NOT NULL DEFAULT '',
  tone TEXT NOT NULL DEFAULT '',
  brand TEXT NOT NULL DEFAULT '',
  category TEXT NOT NULL DEFAULT '',
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS booking_repair_issues (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT NOT NULL DEFAULT '',
  title TEXT NOT NULL DEFAULT '',
  copy TEXT NOT NULL DEFAULT '',
  icon TEXT NOT NULL DEFAULT '',
  tone TEXT NOT NULL DEFAULT '',
  image TEXT NOT NULL DEFAULT '',
  availability TEXT NOT NULL DEFAULT '',
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS review_stats (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  value TEXT NOT NULL DEFAULT '',
  label TEXT NOT NULL DEFAULT '',
  copy TEXT NOT NULL DEFAULT '',
  icon TEXT NOT NULL DEFAULT '',
  tone TEXT NOT NULL DEFAULT '',
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS customer_reviews (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL DEFAULT '',
  date TEXT NOT NULL DEFAULT '',
  copy TEXT NOT NULL DEFAULT '',
  stars TEXT NOT NULL DEFAULT '',
  service TEXT NOT NULL DEFAULT '',
  icon TEXT NOT NULL DEFAULT '',
  tone TEXT NOT NULL DEFAULT '',
  avatar TEXT NOT NULL DEFAULT '',
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS before_after_repairs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device TEXT NOT NULL DEFAULT '',
  service TEXT NOT NULL DEFAULT '',
  copy TEXT NOT NULL DEFAULT '',
  time TEXT NOT NULL DEFAULT '',
  tone TEXT NOT NULL DEFAULT '',
  before_image TEXT NOT NULL DEFAULT '',
  after_image TEXT NOT NULL DEFAULT '',
  kind TEXT NOT NULL DEFAULT '',
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS before_after_testimonials (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL DEFAULT '',
  service TEXT NOT NULL DEFAULT '',
  copy TEXT NOT NULL DEFAULT '',
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS service_hero_trust (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL DEFAULT '',
  copy TEXT NOT NULL DEFAULT '',
  icon TEXT NOT NULL DEFAULT '',
  tone TEXT NOT NULL DEFAULT '',
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS service_cards (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL DEFAULT '',
  copy TEXT NOT NULL DEFAULT '',
  price TEXT NOT NULL DEFAULT '',
  image TEXT NOT NULL DEFAULT '',
  icon TEXT NOT NULL DEFAULT '',
  tone TEXT NOT NULL DEFAULT '',
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS service_trust_features (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL DEFAULT '',
  copy TEXT NOT NULL DEFAULT '',
  icon TEXT NOT NULL DEFAULT '',
  tone TEXT NOT NULL DEFAULT '',
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS service_process_steps (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL DEFAULT '',
  copy TEXT NOT NULL DEFAULT '',
  icon TEXT NOT NULL DEFAULT '',
  tone TEXT NOT NULL DEFAULT '',
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS support_faqs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question TEXT NOT NULL DEFAULT '',
  answer TEXT NOT NULL DEFAULT '',
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS support_quick_actions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL DEFAULT '',
  copy TEXT NOT NULL DEFAULT '',
  icon TEXT NOT NULL DEFAULT '',
  tone TEXT NOT NULL DEFAULT '',
  href TEXT NOT NULL DEFAULT '',
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS support_contact_info (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL DEFAULT '',
  copy TEXT NOT NULL DEFAULT '',
  icon TEXT NOT NULL DEFAULT '',
  tone TEXT NOT NULL DEFAULT '',
  href TEXT NOT NULL DEFAULT '',
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DELETE FROM home_services;
INSERT INTO home_services (title, price, copy, icon, tone, image, sort_order)
SELECT item.value ->> 'title', item.value ->> 'price', item.value ->> 'copy', item.value ->> 'icon', item.value ->> 'tone', item.value ->> 'image', item.ordinality - 1
FROM content_sections, jsonb_array_elements(payload_json -> 'services') WITH ORDINALITY AS item(value, ordinality)
WHERE section_key = 'home';

DELETE FROM home_testimonials;
INSERT INTO home_testimonials (name, service, copy, sort_order)
SELECT item.value ->> 0, item.value ->> 1, item.value ->> 2, item.ordinality - 1
FROM content_sections, jsonb_array_elements(payload_json -> 'testimonials') WITH ORDINALITY AS item(value, ordinality)
WHERE section_key = 'home';

DELETE FROM booking_devices;
INSERT INTO booking_devices (name, image, tone, brand, category, sort_order)
SELECT item.value ->> 'name', item.value ->> 'image', item.value ->> 'tone', item.value ->> 'brand', item.value ->> 'category', item.ordinality - 1
FROM content_sections, jsonb_array_elements(payload_json -> 'devices') WITH ORDINALITY AS item(value, ordinality)
WHERE section_key = 'booking';

DELETE FROM booking_repair_issues;
INSERT INTO booking_repair_issues (key, title, copy, icon, tone, image, availability, sort_order)
SELECT item.value ->> 'key', item.value ->> 'title', item.value ->> 'copy', item.value ->> 'icon', item.value ->> 'tone', item.value ->> 'image', item.value ->> 'availability', item.ordinality - 1
FROM content_sections, jsonb_array_elements(payload_json -> 'repairIssues') WITH ORDINALITY AS item(value, ordinality)
WHERE section_key = 'booking';

DELETE FROM review_stats;
INSERT INTO review_stats (value, label, copy, icon, tone, sort_order)
SELECT item.value ->> 'value', item.value ->> 'label', item.value ->> 'copy', item.value ->> 'icon', item.value ->> 'tone', item.ordinality - 1
FROM content_sections, jsonb_array_elements(payload_json -> 'stats') WITH ORDINALITY AS item(value, ordinality)
WHERE section_key = 'reviews';

DELETE FROM customer_reviews;
INSERT INTO customer_reviews (name, date, copy, stars, service, icon, tone, avatar, sort_order)
SELECT item.value ->> 'name', item.value ->> 'date', item.value ->> 'copy', item.value ->> 'stars', item.value ->> 'service', item.value ->> 'icon', item.value ->> 'tone', item.value ->> 'avatar', item.ordinality - 1
FROM content_sections, jsonb_array_elements(payload_json -> 'reviews') WITH ORDINALITY AS item(value, ordinality)
WHERE section_key = 'reviews';

DELETE FROM before_after_repairs;
INSERT INTO before_after_repairs (device, service, copy, time, tone, before_image, after_image, kind, sort_order)
SELECT item.value ->> 'device', item.value ->> 'service', item.value ->> 'copy', item.value ->> 'time', item.value ->> 'tone', item.value ->> 'beforeImage', item.value ->> 'afterImage', item.value ->> 'kind', item.ordinality - 1
FROM content_sections, jsonb_array_elements(payload_json -> 'repairs') WITH ORDINALITY AS item(value, ordinality)
WHERE section_key = 'beforeAfter';

DELETE FROM before_after_testimonials;
INSERT INTO before_after_testimonials (name, service, copy, sort_order)
SELECT item.value ->> 0, item.value ->> 1, item.value ->> 2, item.ordinality - 1
FROM content_sections, jsonb_array_elements(payload_json -> 'testimonials') WITH ORDINALITY AS item(value, ordinality)
WHERE section_key = 'beforeAfter';

DELETE FROM service_hero_trust;
INSERT INTO service_hero_trust (title, copy, icon, tone, sort_order)
SELECT item.value ->> 'title', item.value ->> 'copy', item.value ->> 'icon', item.value ->> 'tone', item.ordinality - 1
FROM content_sections, jsonb_array_elements(payload_json -> 'heroTrust') WITH ORDINALITY AS item(value, ordinality)
WHERE section_key = 'services';

DELETE FROM service_cards;
INSERT INTO service_cards (title, copy, price, image, icon, tone, sort_order)
SELECT item.value ->> 'title', item.value ->> 'copy', item.value ->> 'price', item.value ->> 'image', item.value ->> 'icon', item.value ->> 'tone', item.ordinality - 1
FROM content_sections, jsonb_array_elements(payload_json -> 'services') WITH ORDINALITY AS item(value, ordinality)
WHERE section_key = 'services';

DELETE FROM service_trust_features;
INSERT INTO service_trust_features (title, copy, icon, tone, sort_order)
SELECT item.value ->> 'title', item.value ->> 'copy', item.value ->> 'icon', item.value ->> 'tone', item.ordinality - 1
FROM content_sections, jsonb_array_elements(payload_json -> 'trustFeatures') WITH ORDINALITY AS item(value, ordinality)
WHERE section_key = 'services';

DELETE FROM service_process_steps;
INSERT INTO service_process_steps (title, copy, icon, tone, sort_order)
SELECT item.value ->> 'title', item.value ->> 'copy', item.value ->> 'icon', item.value ->> 'tone', item.ordinality - 1
FROM content_sections, jsonb_array_elements(payload_json -> 'process') WITH ORDINALITY AS item(value, ordinality)
WHERE section_key = 'services';

DELETE FROM support_faqs;
INSERT INTO support_faqs (question, answer, sort_order)
SELECT item.value ->> 'question', item.value ->> 'answer', item.ordinality - 1
FROM content_sections, jsonb_array_elements(payload_json -> 'faqs') WITH ORDINALITY AS item(value, ordinality)
WHERE section_key = 'support';

DELETE FROM support_quick_actions;
INSERT INTO support_quick_actions (title, copy, icon, tone, href, sort_order)
SELECT item.value ->> 'title', item.value ->> 'copy', item.value ->> 'icon', item.value ->> 'tone', item.value ->> 'href', item.ordinality - 1
FROM content_sections, jsonb_array_elements(payload_json -> 'quickActions') WITH ORDINALITY AS item(value, ordinality)
WHERE section_key = 'support';

DELETE FROM support_contact_info;
INSERT INTO support_contact_info (title, copy, icon, tone, href, sort_order)
SELECT item.value ->> 'title', item.value ->> 'copy', item.value ->> 'icon', item.value ->> 'tone', item.value ->> 'href', item.ordinality - 1
FROM content_sections, jsonb_array_elements(payload_json -> 'contactInfo') WITH ORDINALITY AS item(value, ordinality)
WHERE section_key = 'support';

UPDATE content_sections
SET payload_json = '{}'::jsonb
WHERE section_key IN ('home', 'booking', 'reviews', 'beforeAfter', 'services', 'support');

COMMIT;
